accelerator: null
accumulate_grad_batches: 2
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 4
benchmark: false
bert_config_dir: /home/xiangpan/Labs/CovidQA/mrc-for-flat-nested-ner/cached_models/bert-base-uncased
bert_dropout: 0.1
check_val_every_n_epoch: 1
checkpoint_callback: true
chinese: false
data_dir: /home/xiangpan/Labs/CovidQA/mrc-for-flat-nested-ner/datasets/ace2004
default_root_dir: /home/xiangpan/Labs/CovidQA/mrc-for-flat-nested-ner/train_logs/ace2004/ace2004_20200915reproduce_lr3e-5_drop0.3_norm1.0_bsz32_hard_span_weight0.1_warmup0_maxlen128_newtrunc_debug
deterministic: false
dice_smooth: 1.0e-08
distributed_backend: ddp
enable_pl_optimizer: null
fast_dev_run: false
final_div_factor: 10000.0
flat: false
flush_logs_every_n_steps: 100
gpus: 0,
gradient_clip_val: 1.0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_type: bce
lr: 3.0e-05
max_epochs: 20
max_length: 128
max_steps: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
mrc_dropout: 0.3
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
optimizer: adamw
overfit_batches: 0.0
plugins: null
precision: 16
prepare_data_per_node: true
pretrained_checkpoint: ''
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
span_loss_candidates: pred_and_gold
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse._gpus_arg_default ''
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 0.5
warmup_steps: 0
weight_decay: 0.01
weight_end: 1.0
weight_span: 0.1
weight_start: 1.0
weights_save_path: null
weights_summary: top
workers: 0
